package com.objectstyle.demo.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.objectstyle.demo.cayenne.Article;

/**
 * Class _Domain was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Domain extends CayenneDataObject {

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String ARTICLES_PROPERTY = "articles";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<Article>> ARTICLES = new Property<List<Article>>("articles");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToArticles(Article obj) {
        addToManyTarget("articles", obj, true);
    }
    public void removeFromArticles(Article obj) {
        removeToManyTarget("articles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Article> getArticles() {
        return (List<Article>)readProperty("articles");
    }


}
